<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>be_guardianprotocol.Windows</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SharpHook" Version="7.0.3" />
    <PackageReference Include="System.Diagnostics.PerformanceCounter" Version="9.0.0" />
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\be-guardianprotocol.Core\be-guardianprotocol.Core.csproj" />
  </ItemGroup>

</Project>
